[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/buger/jsonparser"
  branch = "master"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/francoispqt/gojay"
  version = "0.9.1"
